#!/bin/bash
if [[ $# < 1 ]]; then
	echo "Usage: $0 PORT [BAUD]"
	exit
fi

PORT=$1

COMMAND="pio device monitor --echo --filter send_on_enter --port $PORT"

if [[ $2 != "" ]]; then
	COMMAND="$COMMAND --baud $2"
fi

($COMMAND)
